/*
* SPDX-FileCopyrightText: 2024 M5Stack Technology CO LTD
*
* SPDX-License-Identifier: MIT
*/

#define MICROPY_HW_BOARD_NAME "M5STACK Core2"
#define MICROPY_HW_MCU_NAME "ESP32(SPIRAM)"

// Camera configuration for M5Stack PoE CAM (OV3660)
#define MICROPY_HW_CAMERA_PWDN -1
#define MICROPY_HW_CAMERA_RESET 15
#define MICROPY_HW_CAMERA_XCLK 27
#define MICROPY_HW_CAMERA_SIOD 25
#define MICROPY_HW_CAMERA_SIOC 23
#define MICROPY_HW_CAMERA_Y9 19
#define MICROPY_HW_CAMERA_Y8 36
#define MICROPY_HW_CAMERA_Y7 18
#define MICROPY_HW_CAMERA_Y6 39
#define MICROPY_HW_CAMERA_Y5 5
#define MICROPY_HW_CAMERA_Y4 34
#define MICROPY_HW_CAMERA_Y3 35
#define MICROPY_HW_CAMERA_Y2 32
#define MICROPY_HW_CAMERA_VSYNC 22
#define MICROPY_HW_CAMERA_HREF 26
#define MICROPY_HW_CAMERA_PCLK 21
